export const USER_TASK_REQUEST = "USER_TASK_REQUEST";
export const USER_TASK_SUCCESS = "USER_TASK_SUCCESS";
export const USER_TASK_FAIL = "USER_TASK_FAIL";
export const USER_TASK_RESET = "USER_TASK_RESET"

export const ALL_TASKS_REQUEST = "ALL_TASKS_REQUEST";
export const ALL_TASKS_SUCCESS = "ALL_TASKS_SUCCESS";
export const ALL_TASKS_FAIL = "ALL_TASKS_FAIL";
export const ALL_TASKS_RESET = "ALL_TASKS_RESET"

export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";
export const UPDATE_TASK_RESET = "UPDATE_TASK_RESET"

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";
export const DELETE_TASK_RESET = "DELETE_TASK_RESET"